name: lejaum
description: lejaum inc.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Pacote de fontes
  google_fonts: ^2.1.0

  # Pacote de icones
  font_awesome_flutter: ^9.2.0

  # Roda svg
  flutter_svg: ^0.22.0

  # Hover nos botões da appBar
  hovering: ^1.0.4

  # State management
  get: ^4.6.1


  # Responsividade
  responsive_framework: ^0.1.5
  sizer: ^2.0.15

  # Roda video
  video_player: ^2.2.10
  
  # Abre link web
  url_launcher: ^6.0.17

  # SEO?
  seo_renderer: ^0.3.0

  # Text Size
  auto_size_text: ^3.0.0

  # PDF
  syncfusion_flutter_pdfviewer: ^19.4.43-beta
  pdf_render: ^1.0.21
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/boxes/
    - assets/images/icons/
    - assets/images/galeria/social_media1/png/
    - assets/images/galeria/social_media1/webp/
    - assets/images/galeria/social_media2/
    - assets/images/galeria/azardi/
    - assets/images/galeria/janfie/
    - assets/images/galeria/italo/
    - assets/images/galeria/lejaum/
    - assets/images/
    - assets/pdf/
    - assets/svgs/
    - assets/videos/

  fonts:
    - family: Georama
      fonts:
        - asset: assets/fonts/Georama/Georama-Regular.ttf
          weight: 400
        - asset: assets/fonts/Georama/Georama-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Georama/Georama-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Georama/Georama-Bold.ttf
          weight: 700
        - asset: assets/fonts/Georama/Georama-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Georama/Georama-Black.ttf
          weight: 900
