name: Pushzada - Att
on: push
jobs:
    hosting:
      name: Rodando repositório
      runs-on: ubuntu-latest
      steps:
        # Checkout Repository
        - uses: actions/checkout@v3

        # Install Flutter command
        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable'

        # Build Website
        - name: Construindo Site
          run: |
            flutter pub get
            flutter build web
        # flutter config --enable-web
        # flutter pub get
        # flutter build web --release 
          working-directory: ./

        # Deploy Firebase Hosting
        - name: Enviando para o Firebase
          uses: w9jds/firebase-action@master
          with:
            args: deploy --only hosting:lejaum-web-app
          env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
            PROJECT_PATH: ./